version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: web_service
    ports:
      - "8080:80"  
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db_service
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  pgdata:  

networks:
  app_net:  
    driver: bridge
